services:
  - type: web
    name: birlik-elektrik
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    staticPublishPath: ./
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /admin/*
        destination: /admin/:splat
      - type: rewrite
        source: /*
        destination: /index.html 