services:
  - type: web
    name: birlik-elektrik
    env: static
    buildCommand: echo "Static site deployment"
    staticPublishPath: ./
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 